### ISSUE TITLE
[Bug]:  Class: DataObject\Concrete => call to undefined static method getBykey

### ISSUE THREAD

**Issue by danielczestki** [pimcore/data-importer#104]
### Expected behavior

Load object by its System Key

### Actual behavior

ERROR

### Steps to reproduce

Add mapping for field and use Transformation Load DataObject and load it by SYSTEM key attribute.

**Comment by fashxp** [comment]
needs to be solved via https://github.com/pimcore/pimcore/issues/10710

**Comment by jtwogw** [comment]
Same issue on Pimcore 11.1.5 
![image](https://github.com/pimcore/data-importer/assets/13637470/98eef59d-6f4d-40bd-b04e-e2b320e84f5d)
![image](https://github.com/pimcore/data-importer/assets/13637470/fb7b7ac7-30c0-4809-a902-257495f984a3)

**Comment by fashxp** [comment]
hmm, strange ... cannot reproduce it anymore ... and also code wise it should work.
