### ISSUE TITLE
[Bug]: composer requirements Pimcore ^6.8 but Pimcore 6.9 feature used

### ISSUE THREAD

**Issue by fweisflug** [pimcore/data-importer#113]
### Expected behavior

bundle should either work with pimcore 6.8 or requirments need to be updated.

### Actual behavior

import preview fails because the function getLocalFileFromStream used from the Pimcore\File\TemporaryFileHelperTrait Trait is not available on Pimcore 6.8 and was only added with Pimcore 6.9.

### Steps to reproduce

install data-importer >=1.2 on pimcore 6.8.x. use the import preview under import settings.

the getLocalFileFromStream function used from the Pimcore\File\TemporaryFileHelperTrait was only added in Pimcore 6.9 (https://github.com/pimcore/pimcore/blob/v6.9.0/lib/Helper/TemporaryFileHelperTrait.php#L82-L94) but is missing on the latest 6.8 tag (https://github.com/pimcore/pimcore/blob/v6.8.12/lib/Helper/TemporaryFileHelperTrait.php).

either the composer requirement/constrain (https://github.com/pimcore/data-importer/blob/1.x/composer.json#L10) needs to be updated or the code adjusted.

**Comment by fashxp** [comment]
need to bump requirement to 6.9

**Comment by dvesh3** [comment]
Fixed by #119
