### ISSUE TITLE
[Bug]: datahub:data-importer:process-queue-parallel / run from cron doesn not work

### ISSUE THREAD

**Issue by danielczestki** [pimcore/data-importer#114]
### Expected behavior

running import

### Actual behavior

console.ERROR: Error thrown while running command "datahub:data-importer:process-queue-parallel --processes=5". Message: "Expected a string. Got: boolean" {"exception":"[object] (Webmozart\\Assert\\InvalidArgumentException(code: 0): Expected a string. Got: boolean

### Steps to reproduce

in vendor/webmozarts/console-parallelization/src/Parallelization.php:358
we have:
`$consolePath = realpath(getcwd().'/bin/console');`

If I run by cron this command:
`*/5 * * * * php /home/project/www/bin/console datahub:data-importer:process-queue-parallel --processes=5`

the getcwd() return '/' and $consolePath is false and I got error:

console.ERROR: Error thrown while running command "datahub:data-importer:process-queue-parallel --processes=5". Message: "Expected a string. Got: boolean" {"exception":"[object] (Webmozart\\Assert\\InvalidArgumentException(code: 0): Expected a string. Got: boolean

If I run direct from console but from /home/project/www directory everything works fine.

**Comment by fashxp** [comment]
what Pimcore / Data-Importer versions you are using?

**Comment by danielczestki** [comment]
PimCore 6.9.6
DataHub: 1.0.5
DataHub Importer: 1.1.3

**Comment by skoch-twocream** [comment]
Hi, let's see if I can help

This trait:
https://github.com/pimcore/pimcore/blob/10.x/lib/Console/Traits/Parallelization.php#L163

is used in the named command: https://github.com/pimcore/data-importer/blob/1.x/src/Command/ParallelProcessQueueCommand.php#L27

The constant is deined here: https://github.com/pimcore/pimcore/blob/6.9/lib/Bootstrap.php#L111

To solve this temporarily you can simply go into the directory:
` */5 * * * * cd /home/project/www/ && php bin/console datahub:data-importer:process-queue-parallel --processes=5`

Or define an ENV variable:
` */5 * * * * PIMCORE_PROJECT_ROOT=/home/project/www/ php /home/project/www/bin/console datahub:data-importer:process-queue-parallel --processes=5`

**Comment by fashxp** [comment]
should be fixed in Pimcore X ... 
for Pimcore 6.9 please use the suggestion of @skochTC
