### ISSUE TITLE
[Bug]:  non UTF-8 character errors

### ISSUE THREAD

**Issue by QuarkWave** [pimcore/data-importer#115]
### Expected behavior

First, thanks for this extension, without it i would havn't been able to migrate to Pimcore X.

**Issue :**

When importing a file the process should be able to deal with anything we through at it without crashing

### Actual behavior

Errors ... because `json_encode` return a `null` when a non UTF-8 character is present and the following methods are waiting for an array so it failed

### Steps to reproduce

Import any CSV with a non UTF-8 character (like an nonbreaking space ,  asian currency sign, ...)

**Solution ?**

Adjust processImportRow in AbstractInterpreter.php 

**from :**
`$this->queueService->addItemToQueue($this->configName, $this->executionType, ImportProcessingService::JOB_TYPE_PROCESS, json_encode($data));`

**to :**
`$this->queueService->addItemToQueue($this->configName, $this->executionType, ImportProcessingService::JOB_TYPE_PROCESS, json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));`

**Comment by mcop1** [comment]
@QuarkWave could you please upload a basic example file, which we can use to reproduce the issue? That would help us a lot. 
Thank you for you efforts!

**Comment by mittererr** [comment]
Same problem here. The solution provided by @QuarkWave does the trick for me. I can not provide the CSV file of my current use case, because there are address data in it.

**Comment by robertSt7** [comment]
@QuarkWave , @mittererr Sorry, I am not able to reproduce it. Could you please provide the exact characters? Thanks

**Comment by kingjia90** [comment]
Closing due inactivity
