### ISSUE TITLE
[Bug]: union types in PHP 7.4 ??

### ISSUE THREAD

**Issue by danielczestki** [pimcore/data-importer#118]
### Expected behavior

Everything should work without error.

### Actual behavior

> Pimcore\Composer::clearCache

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected '|', expecting ';' or '{' in /home/pim/vendor/pimcore/data-importer/src/Resolver/Resolver.php:177

### Steps to reproduce
installed version: 1.1.3
run: composer update pimcore/data-importer

DEBUG:
Repo File: https://github.com/pimcore/data-importer/blob/v1.3.0/src/Resolver/Resolver.php

Line 177:
When I browse source direct in github or use composer install I see:

public function loadOrCreateAndPrepareElement(array $inputData, bool $createNew = true): ElementInterface | null

Return type use union types which is not allowed in PHP 7.4.

BUT

When I clone project I see this line is correct
public function loadOrCreateAndPrepareElement(array $inputData, bool $createNew = true): ?ElementInterface

The problem is with TAG v.1.3.0. The source code with this tag have issue with return union types.

**Comment by danielczestki** [comment]
@fashxp can someone fix it ?

**Comment by blankse** [comment]
@danielczestki Is already fixed in the 1.3 branch and will be part of v1.3.1 (which should be tagged today)
See https://github.com/pimcore/data-importer/pull/110
