### ISSUE TITLE
[Bug]: Unable to upload data object using Data Importer

### ISSUE THREAD

**Issue by dezaidamalek** [pimcore/data-importer#130]
### Expected behavior

Data from .xslx sheet (which is already uploaded into Asset) is supposed to be uploaded as data object. 

### Actual behavior

Data from .xslx sheet (which is already uploaded into Asset) is not uploaded once manual execution is triggered. Below image stay the same for hours.

![data importer](https://user-images.githubusercontent.com/45670306/142992917-89af83aa-c066-481f-bfd5-711c1368c752.png)

### Steps to reproduce

1. Go to Datahub
2. Add Configuration > Data Object Importer > Create new importer
3. Data Source > Type: Asset > Asset: select .xslx from Asset 
4. Configure in Import Setting
5. Execution > Manual Execution

**Comment by mcop1** [comment]
@dezaidamalek when you click on the "Start" button for manual execution, your import is put into a queue. But you still have to consume the queue. Please try to run one of the commands mentioned here https://pimcore.com/docs/data-importer/current/Installation.html ("Bundle Configuration"). 

E.g. use this command if you are using the parallel execution type:

```
# Process import queue items that can be executed in parallel
*/5 * * * * php /home/project/www/bin/console datahub:data-importer:process-queue-parallel --processes=5
```
or use this command if you are using the sequential execution type:

```
# Process import queue items that need to be executed sequentially 
*/5 * * * * php /home/project/www/bin/console datahub:data-importer:process-queue-sequential 
```

If you have any questions, don´t hesitate to ask.

Best regards

**Comment by mcop1** [comment]
Closed due to inactivity.
