### ISSUE TITLE
Can´t map various fields in Object Bricks 

### ISSUE THREAD

**Issue by Chris-Gett** [pimcore/data-importer#136]
Duplicate of https://github.com/pimcore/data-hub/issues/443
please remove this issue 443 (wrong repo)

Expected behavior
Mapping of all created fields in Objects Bricks which are assigned to the selected data object.

### Actual behavior

I cannot map most of the fields that are created as object bricks in data objects using the Data Importer. I also can't find a comprehensible scheme according to which criteria they don't appear in the mapping.
Here an example:
Fieldname which i could not find in the Mapping Dropdown:
product_graduated_price_salespartner_26_51 [numeric]
which ist content of the Brick "Sales"
Sometimes only single fields from the object bricks are affected..

### Steps to reproduce

just try to map numeric fields or select fields in the importer, I could not yet find a traceable logic to this behavior.

**Comment by fashxp** [comment]
datatype of the target field must match the transformation result. 
of example, if you want to assign values to a numeric value, you need to transform the imported data to a numeric value. 

![image](https://user-images.githubusercontent.com/8792145/144269387-935c66ab-6975-4f9f-9597-ce930da27f6e.png)

**Comment by Chris-Gett** [comment]
Thanks for the hint! That seems to be the solution. A hint in the documentation would be good, that saves nerves and prevents gray hair ;-) or have I overlooked the hint?

**Comment by fashxp** [comment]
https://pimcore.com/docs/data-importer/current/Configuration/Mapping_Configuration/Data_Target/index.html

![image](https://user-images.githubusercontent.com/8792145/144402068-3abb34c4-5c1e-4f17-8d9f-576f65334f35.png)

Any improvements are highly appreciated!

**Comment by Chris-Gett** [comment]
I had read that, but not directly related to it. maybe the following note would be good: "the availability of the fields depends on the settings of the transformation pipeline".

**Comment by fashxp** [comment]
here we go https://github.com/pimcore/data-importer/commit/d2d062582f6a7729536028ad070c6d1bcd0952f8
