### ISSUE TITLE
[Bug]: Empty value gets converted to 0 in Quantity Value Mapper 

### ISSUE THREAD

**Issue by ulbrich-media** [pimcore/data-importer#143]
### Expected behavior

An empty string should be imported as a null value by the Quantity Value Mapper. Empty probably means that there is no value for that record, so 0 is the wrong representation. 

Even better: Don't set the Quantity Value at all, so Pimcores inheritance can do its magic. 

### Actual behavior

An empty string value gets converted to 0 by Quantity Value Mapper. 

This happens because the floatval function will always return a valid float value and uses 0 as a fallback. 
https://github.com/pimcore/data-importer/blob/2f1b7a4598e5e69f64435ebd39f9527fee1964e7/src/Mapping/Operator/Factory/QuantityValue.php#L89

### Steps to reproduce

We have a csv file with technical data. During import there can be a numerical value or the field ist just empty if there is no value for that property. 

1. Create an import configuration 
2. Add a Quantity Value Mapper
3. Add a csv file with empty strings for the mapper 
4. Run import, the imported quantity value is now set to 0 (the mapping preview already shows the problem) 

I can gladly provide a pull request since the fix should be quite simple. I just wanted to check in with you first since I'm not sure if this is expected behaviour and I'm missing something.

**Comment by fashxp** [comment]
I would say, null should be null, so that inheritance can work. 
Would love to see a PR.

**Comment by Chris-Gett** [comment]
I can confirm the behavior.
 it's pretty nerdy, especially when you import prices or other numbers. Empty values are overwritten with 0 although they must remain _NULL_ for the inheritance to work properly. 
Only if an imported value is 0 should 0 be imported as a value I consider this a basic functionality and see no logical reason why _NULL_ should be imported as 0.
I am surprised that no one has reacted to this behavior.

**Comment by Chris-Gett** [comment]
@fashxp is that Problem aleady fixed with that issue #181 ? I think these two issues are more or less related to each other.

**Comment by fashxp** [comment]
true ...
