### ISSUE TITLE
[Improvement]: str_replace operator in the mapping transformation pipeline

### ISSUE THREAD

**Issue by thomas-udalrik** [pimcore/data-importer#150]
### Improvement description

Hi,

I need to import data from a HTTP data source where float values have the "12,99" (comma) format instead of the "12.99" (dot) format.

With the "explode" and "combine" operators I found a way to achieve the conversion before passing the value to the "quantity value" operator.

These questions came up:
1. Is this the way to go or did I miss some other option?
2. What does this mean regarding import performance?

Possible improvement:
A str_replace operator could reduce the currently two steps in the transformation pipeline to only one.
And this would save some PHP operation performancewise.

Thx & regards

![image](https://user-images.githubusercontent.com/13256547/148704278-c8f208b4-52d5-40e5-989c-1306f57fab4c.png)

**Comment by fashxp** [comment]
we should add a str_replace operator
