### ISSUE TITLE
[Bug] Many To Many Relation data target allows all sort of target fields thus creating invalid mappings

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-importer#161]
### Expected behavior

cannot create invalid mapping configuration. 

many-to-many-relation data target should only be allowed when having assets/dataobject (array) as transformation result, and only should provide relation fields as possible data target

### Actual behavior

many-to-many-relation data target allows non-relation fields as data target

### Steps to reproduce

create mapping with many-to-many-relation data target and see selectable fields

![image](https://user-images.githubusercontent.com/8792145/152114705-55b3d0cb-7aef-4b59-8d1c-4a89ab7b63fb.png)

**Comment by mcop1** [comment]
Resolved by #187
