### ISSUE TITLE
[Bug]: Error opening Data Objects Importer configuration after upgrading pimcore/data-hub to v1.2.1

### ISSUE THREAD

**Issue by tiberioalunni** [pimcore/data-importer#166]
### Expected behavior

Clicking the Data Objects Importer configuration the editor should appear

### Actual behavior

nothing appear clicking the import configuration 

into the browser console there is a error reporting:

pimcore.plugin.datahub.adapter[adapterType] is not a constructor

### Steps to reproduce

upgrade pimcore/data-hub to v1.2.1 from v1.2.0

### workaround
downgrade pimcore/data-hub to v1.2.0

### installed version packages
pimcore/data-hub to v1.2.1
pimcore/data-importer v1.4.1

**Comment by mcop1** [comment]
@tiberioalunni sorry, I couldn´t reproduce the issuse. Is it possible for you, to share one of your data importer configurations, please?

**Comment by tiberioalunni** [comment]
> @tiberioalunni sorry, I couldn´t reproduce the issuse. Is it possible for you, to share one of your data importer configurations, please?

This is the configuration file I have in `var/config/data-hub` folder:

[CTEDynamicValueImporter.zip](https://github.com/pimcore/data-importer/files/8097563/CTEDynamicValueImporter.zip)

I have updated Pimcore and dependencies today to version:
pimcore/pimcore to v1.3.1
pimcore/data-hub to v1.2.2
pimcore/data-importer v1.4.2

and the bug is not more present.
