### ISSUE TITLE
[Improvement]: Use Symfony Messanger

### ISSUE THREAD

**Issue by micru** [pimcore/data-importer#167]
### Improvement description

I wonder if there is a reason why symfony messanger is not used for the Pimcore Importer? This Symfony Component offers a lot more flexibility, especially in terms of the transport path for asynchronous processing and queue handling. To process the import queues purely via the database, which by the way would also be possible with the Symfony Messanger, seems to be a big limitation to me. We would like to use more reliable and scalable solutions for this, such as RabbitMQ or Amazon SQS, which has been proven in the enterprise field for a long time. The Symfony Messanger component offers all the necessary abstraction for this and also already brings adapters for frequently used and more robust transports like the two previously mentioned.

https://symfony.com/doc/current/messenger.html

**Comment by fashxp** [comment]
reason up to now are following two aspects: 
- for some imports it is necessary that they need to be executed in a sequential way in exactly the defined order of the import file (because later rows might rely on sooner rows, e.g. for building up hierarchies) 
- other imports could be executed in parallel and thus speed up significantly - which is archived with the parallelization command. 
- providing information about import progress and left items 

we are open to messenger based solutions though, if we find solutions for these two aspects. 
also an option would be to  provide an additional execution type `messenging queue` (besides `parallel` and `sequential`).

**Comment by micru** [comment]
nice to hear that you are generally open for a messanger based approach. 

Regarding sequential processing: at least RabbitMQ and Amazon SQS are _FIFO_ or can be configured accordingly. For other transports this would have to be clarified.
For parallel processing several workers could be started, which may have different/unique _MESSENGER_CONSUMER_NAME_.

A queue/topic would have to exist for each processing mode.

With the Symfony Messanger, each message consists of an envelop object (defined by its own PHP class), which could contain meta data like a unique _importJobId_, the number of associated entries and the sequence number of the current entry in addition to the actual payload (in this case an ImportItem). Maybe the overall progress could be determined by this. 
In addition, it could be useful to define a result queue in which an info about a processed entry is reported. A worker/consumer listening to this queue could thus determine the total progress of an import job and also additional information such as the total number of processed entries since the start of the worker or similar.

Besides the already mentioned flexibility and scalability, i see the additional advantage when using the Symfony Messanger that there is almost no latency. As soon as a new import is received, the first entry is processed immediately because the workers are always running, achieved by an endless running command. Therefore there is no waiting time until the next run of a cron job occurs, provided the workers are not still busy with previous imports.

**Comment by fashxp** [comment]
any PR drafts to outline the approach are welcome. 
we definitely need to keep performance in mind though - our current experience with queues is, that they produce lots of overhead too ... see also https://github.com/pimcore/pimcore/pull/11399

**Comment by fashxp** [comment]
see #179

**Comment by cancan101** [comment]
Are there any pros / cons to using the "Symfony Messenger Based" vs the "Command Based" importer? The [docs offer both options](https://docs.pimcore.com/platform/Data_Importer/Installation#import-execution), but do not provide any guidance as to which to use. e.g. https://github.com/pimcore/data-importer/issues/194#issuecomment-2933186580
