### ISSUE TITLE
[Bug]: JS error, config button not available

### ISSUE THREAD

**Issue by valentin-** [pimcore/data-importer#169]
### Expected behavior

Open the config.

### Actual behavior

I've installed and enabled the bundle. The datahub bundle is activated as well.

The config button for the data importer won't get injected, as the source is not valid - properties[0] is undefined. 

![image](https://user-images.githubusercontent.com/90033/153582167-96010d2e-b653-4844-abd0-7378e09ba2df.png)

Any idea why this empty key is present?

Pimcore version 10.3.

### Steps to reproduce

Install data importer bundle, open backend.

**Comment by fashxp** [comment]
what is the exact error message?

**Comment by valentin-** [comment]
This is the output

![image](https://user-images.githubusercontent.com/90033/153608608-a7f5213c-2dfd-410a-bfba-3513eac02ae5.png)

**Comment by valentin-** [comment]
This also occurs in another 10.3 project without any other extensions enabled.

**Comment by mcop1** [comment]
@valentin- sorry I am not able to reproduce the issue on my side. I used the skeleton (https://github.com/pimcore/skeleton) and installed datahub + data-importer. But everything works just fine.

**Comment by valentin-** [comment]
Sorry that was my fault, after setting the priority as described in the documentation it's working.

**Comment by neha04** [comment]
@valentin- i am facing same issue . How did you fixed that issue?
