### ISSUE TITLE
[Bug]: Undefined class constant 'CONFIGURATION_POST_SAVE' if DataHub version too low

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/data-importer#176]
### Expected behavior

Update Importer Bundle from v1.3.1 to v1.3.3 or till latest 1.3.x because of https://github.com/pimcore/data-importer/issues/125

DataHub is still on 1.0.11

### Actual behavior

Crit Error: Undefined class constant 'CONFIGURATION_POST_SAVE'

Constant "CONFIGURATION_POST_SAVE" was implemented in DataHub v10.1.0 https://github.com/pimcore/data-hub/blob/v1.1.0/src/Event/ConfigurationEvents.php

This should be considered in the composer.json

### Steps to reproduce

Update Importer Bundle from v1.3.1 to v1.3.3 or till latest 1.3.x

DataHub is still below v10.1.0

**Comment by fashxp** [comment]
1.3 branch is not supported anymore.

**Comment by fashxp** [comment]
if somebody is willing to provide a fix for it, we would reopen a 1.3 branch, merge it and tag another 1.3-release.

**Comment by RuudvdvNB** [comment]
@fashxp why are you not supporting the 1.3 branch anymore and are you depending on the community? For customers with Pimcore 6.9 LTS this bundle is still unavailable now?

**Comment by fashxp** [comment]
@RuudvdvNB it is simple a resource topic. If a LTS customer needs it, please get in contact with us, then we can figure out something for sure.
