### ISSUE TITLE
[Bug]: JavaScript TypeError: pimcore.plugin.datahub.adapter[adapterType] is not a constructor

### ISSUE THREAD

**Issue by thomas-udalrik** [pimcore/data-importer#178]
### Expected behavior

Existing Data-Importer Profiles open

### Actual behavior

Existing Data-Importer Profiles don't open without any output in the frontend.

There is a console error:
`TypeError: pimcore.plugin.datahub.adapter[adapterType] is not a constructor`

![grafik](https://user-images.githubusercontent.com/13256547/156403452-18f34c34-0771-44ee-a60a-4c29fb5370fc.png)

![grafik](https://user-images.githubusercontent.com/13256547/156403587-378f0446-6570-4932-ae85-731635d7b809.png)

I flushed the browser cache, without any effect.

### Steps to reproduce

composer.lock
```
...
 "name": "pimcore/pimcore",
            "version": "v10.3.2",
...
"name": "pimcore/data-hub",
            "version": "v1.2.3",
...
"name": "pimcore/data-importer",
            "version": "v1.4.3",
...
```

1. Open Datahub
2. Click on an existing data-importer profile

**Comment by rjankiew** [comment]
It started to occur for me as well, after updating pimcore from 10.2.7 to 10.3.2

**Comment by fashxp** [comment]
did you execute all migrations of data-importer bundle? 

please make sure, they are executed and the data-importer bundle is activated properly.

**Comment by rjankiew** [comment]
@fashxp that was it, the migration was not auto-executed during composer install. Thanks for the help!
