### ISSUE TITLE
[Feature]: LoadByAttribute to include variants

### ISSUE THREAD

**Issue by milesimarco** [pimcore/data-importer#180]
### Feature description

Element Loading strategy byAttribute doesn't seems to include OBJECT_TYPE_VARIANT in the resolver (only OBJECT_TYPE_OBJECT).
However, variants are correctly working with ID/PATH strategy.

This leads to the `No match by AttributeStrategy with 'Do not create' location strategy` error.

![Annotation](https://user-images.githubusercontent.com/3340185/157252705-4a6abb76-09a2-4df6-a9dd-cea9eac408a3.jpg)

What do you think to support variants by attribute in data importer?

Best regards,
M.

**Comment by fashxp** [comment]
I would even classify that as a bug.

**Comment by mcop1** [comment]
Resolved by #183

**Comment by mohammed-mahmoud-scandi** [comment]
I have configured my data importer in the following way to support adding variants to their parents
![image](https://user-images.githubusercontent.com/121216666/230358783-3c534209-3136-4327-9e5a-1812439a647e.png)
and it's working well, but child objects added as objects not variants 
![image](https://user-images.githubusercontent.com/121216666/230358920-af5f7337-f6fd-4037-adb4-4f9eb76bfd4d.png)
though my class supports adding variants
![image](https://user-images.githubusercontent.com/121216666/230359071-c4f15353-23fb-433e-a4f9-309ea1f79b7c.png)
and I can add variants manually 
![image](https://user-images.githubusercontent.com/121216666/230362633-335a898a-834f-4c64-9cd2-6c12cde802c5.png)
Though I went through this  issue which should resolve my issue https://github.com/pimcore/data-importer/issues/180
but it seems issue still here

**Comment by mohammed-mahmoud-scandi** [comment]
is there's something I miss @mcop1
