### ISSUE TITLE
[Bug]: Cant stop command from Datahub

### ISSUE THREAD

**Issue by tebulrich** [pimcore/data-importer#194]
### Expected behavior

We wanted to import some data. Via SSH, we connected to the server. The client computer crashed and now we have this:

pimcore@pimcore:/var/www/html/pimcore$ php /var/www/html/pimcore/bin/console datahub:data-importer:process-queue-parallel --processes=50
ERROR: The command is already running.

I couldnt find anything how to stop this. I assume, there is some lock file or something since i restarted the server, killed all PHP processes and this error still comes up.

### Actual behavior

See above

### Steps to reproduce

See above

**Comment by tebulrich** [comment]
Edit: just saw, there is a key in the lock_keys table. Deleted it and it worked again. Maybe could be documented somewhere.

**Comment by brusch** [comment]
Moved to pimcore/data-hub

**Comment by mcop1** [comment]
I added a troubleshooting section to the data-importer documentation, explaining the problem and solution
https://github.com/pimcore/data-importer/pull/212

**Comment by cancan101** [comment]
Does the lock apply only to the command based importer or does it apply to the messenger based importer as well? i.e. if I use the messenger approach, can I have multiple imports running in parallel.
