### ISSUE TITLE
[Bug]: Classification Store Batch - input quantity value

### ISSUE THREAD

**Issue by rjankiew** [pimcore/data-importer#210]
### Expected behavior

Imported values are visible is CS group in "Edit" tab when object is opened.

### Actual behavior

Imported values are visible only on latest object version in the "Versions" tab, where values and units are assigned as expected. 

However, value and unit is empty (has previous value) on "Edit" tab. As field data is loaded on UI as empty, saving an object erases value and unit even from newly created version in "Versions" tab.

### Steps to reproduce

Create an import config that will import input quantity value attributes (value + unit) using "Classification Store Batch" data target, according to the docs. I used import from xlsx with "#" character separating value from unit. Run the import, and open modified objects "Edit" tab after it has finished.

As I imagined this could be versioning-related, I tested this for both published and unpublished (and even never ever published) objects, but the result is always the same for me, and values are not visible on "Edit" tab.

**Comment by robertSt7** [comment]
Sorry, but I can't reproduce the bug. 
Could you please provide a xlsx file with some dummy data and a screenshot of the transformation pipeline?

**Comment by rjankiew** [comment]
@robertSt7 sorry for long time with no response, I wanted to update pimcore and data-importer to see if this will fix the issue. 

I'm now using pimcore 10.4.3 and data-importer 1.6.0, and unfortunately this behaviour continues.

This is data in xlsx file that I'm using:
id | group-parameter | value
-- | -- | --
test-import-iqv | 6-13 | 666#8
test-import-iqv | 6-17 | 20#1

This is transformation pipeline:
![pipeline](https://user-images.githubusercontent.com/89988908/174789087-f7f21b94-965f-4892-b8be-0c43bc57d86a.png)

The logs seem fine:
![logs](https://user-images.githubusercontent.com/89988908/174789279-bcb00d52-22f2-433b-a4e7-c13ccb866824.png)
