### ISSUE TITLE
No package available on Packagist.org

### ISSUE THREAD

**Issue by alexdrupal** [pimcore/data-importer#22]
Hello

Guys I cannot install the extension due to:

`Could not find a matching version of package pimcore/data-importer. Check the package spelling, your version   
  constraint and that the package is available in a stability which matches your minimum-stability (stable). `

Tried ti set minimum stability - no luck. Checked on packagist.org repo and don't found the extension.
Please add it to the packagist.org
Thank you!

**Comment by fashxp** [comment]
you need to add the package directly to your composer.json at the moment.
will be added to packagist as soon as we release first version.
