### ISSUE TITLE
[Bug]: Unable to append or prepend "0" with Static Text operator

### ISSUE THREAD

**Issue by luca-mussoni-extera** [pimcore/data-importer#224]
### Expected behavior

Every string is appended or prepended correctly, even "0".

### Actual behavior

Nothing is added to the string.
If you configure a Static Text operator with "0" as text, it doesn't pass the initial check:
`if ($this->text)`

### Steps to reproduce

Configure a Static Text operator in the transformation pipeline with the text "0".

For a possible solution I suggest to check only for empty strings:
`if ($this->text !== '')`

**Comment by robertSt7** [comment]
@luca-mussoni-extera  Thank you for reporting the bug. Since you have already described the solution, do you also like to create the PR?
