### ISSUE TITLE
[Bug]: Exception in Data-Importer

### ISSUE THREAD

**Issue by kamilawiercinska** [pimcore/data-importer#228]
### Expected behavior

Data-importer configuration is saved and user is able to go to another configuration to modify it.

### Actual behavior

Error: Server threw exception - could not perform action. Please reload the admin interface and try again.
![image](https://user-images.githubusercontent.com/49391646/177494522-bc314453-b18d-47c3-b51f-e9809c89e77c.png)

 Configuration list is empty and user is not able to select another configuration
![image](https://user-images.githubusercontent.com/49391646/177494655-8a1d6309-95c4-4a49-8527-a4965621a2a2.png)

### Steps to reproduce

1. Open DataHub
2. Select data-importer configuration
3. Modify configuration
4. Click Save

**Comment by mcop1** [comment]
@kamilawiercinska Hello,

I created a new pimcore demo environment, installed data-hub and data-importer, created a new config, but couldn´t reproduce the issue.
Which versions of data-hub/data-importer are you using? Can you reproduce the issue on our demo https://demo.pimcore.fun?

**Comment by mcop1** [comment]
Closed due to inactivity. Feel free to comment, if you have any further details regarding this topic.
