### ISSUE TITLE
[Bug]:  Transformation Load DataObject ignores Class when using SYSTEM KEY as attribute

### ISSUE THREAD

**Issue by dasysdev** [pimcore/data-importer#242]
### Expected behavior

On Column Mappings > Transformation Pipeline > Load Data Object codition 'Class' must be applied when searching DataObject with attribute SISTEM key.

### Actual behavior

It seems to ingore the Class as a condition in the DataObject searching and it is loading first object found with matching SYSTEM Key

**conditions applied correctly when using a custom field attirbute (used as a workarround)

### Steps to reproduce

1. add column mapping
2. add Transformation step of type Load Data Object
3. configure as follows: 'Load DataObject via: Attribute'; 'Class: ExampleClass';  'Attribute Name: SISTEM Key'
4. Transformation Result: Preview not matching what expected

**Comment by mcop1** [comment]
Hello @dasysdev ,
seems like it is working for me. I have multiple data objects with key "hood ornaments", but the data-importer is loading the expected object with class `Category`:
![grafik](https://user-images.githubusercontent.com/89011527/197746211-841d586e-91f3-4d75-857b-bb1fdb735c08.png)

Which version of data-importer are you using? We introduced a `DataObjectLoader` (https://github.com/pimcore/data-importer/pull/157) in February, maybe this would resolve your problem?

**Comment by mcop1** [comment]
@dasysdev any chance you had some time to look at my comment?

**Comment by mcop1** [comment]
Issue closed due to inactivity. Feel free to reopen again.
