### ISSUE TITLE
[Bug]: AbstractLoad type conflict in __construct()

### ISSUE THREAD

**Issue by robertSt7** [pimcore/data-importer#246]
### Expected behavior

No TypeError is thrown

### Actual behavior

Pimcore\Bundle\DataImporterBundle\Resolver\Load\AbstractLoad::__construct(): Argument 1 ($connection) must be of type Pimcore\Db\ConnectionInterface, Doctrine\DBAL\Connection given, called in /var/www/html/var/cache/dev/Container4gyT3Zg/getResolverFactoryService.php on line 47

### Steps to reproduce

- Checkout 11.x
- Login

**Comment by blankse** [comment]
See https://github.com/pimcore/data-importer/pull/245
