### ISSUE TITLE
[Bug]: Import of manty-to-many relation not possible

### ISSUE THREAD

**Issue by georgringer** [pimcore/data-importer#254]
### Expected behavior

If the import data holds multiple IDs, all relations should be added.

### Actual behavior

Only if one relation is provided, this will be created.

### Steps to reproduce

Kind of same issue: https://github.com/pimcore/data-importer/issues/80.

I got the following sample JSON
```json
"categoryList": "id1370904",
        "categoryPaths": "/Kategorien/Pflanzen/Stauden,/Kategorien/Pflanzen/Gemüsepflanzen,/Kategorien/Saisonelles/Gemüsepflanzen",
        "categoryPimcore": "1907,2069",
        "categoryPaths2": "/Kategorien/Pflanzen/Stauden",
        "categoryPimcore2": "1907"
```

this is to test if the issue is about paths, custom property or ID of an object but neither of those can handle imports of multiple relations.

**Example 1**: If the field with one ID/path is used

![image](https://user-images.githubusercontent.com/1905663/189651164-5d4e7957-8967-4932-90e7-053c8ce1f4a7.png)

**Example 1**: If the field with multiple IDs/paths is used

![image](https://user-images.githubusercontent.com/1905663/189651337-f1290811-bb25-4f95-a5f8-60fd20673b08.png)

**Comment by mcop1** [comment]
Hello @georgringer 

loadDataObjects works with arrays, could you please try to explode the values into an array first? Like this:
![grafik](https://user-images.githubusercontent.com/89011527/191734250-642a6e95-22f1-49af-b21f-c2b2fe5365c3.png)

**Comment by mcop1** [comment]
I am closing this issue for now, if you have any questions feel free to reopen it.
Thanks!
