### ISSUE TITLE
[Task]: Replace abandoned package `league/flysystem-sftp` 

### ISSUE THREAD

**Issue by kingjia90** [pimcore/data-importer#274]
https://github.com/pimcore/data-importer/blob/f18da3b9b841b271dff12f7c921056e7b58ee1d8/composer.json#L19
It appears to be [outdated](https://github.com/thephpleague/flysystem-sftp#caution-this-package-is-deprecated-since-flysystem-30-instead-use-the-flysystem-for-sftp-v3)
the correct one is `"league/flysystem-sftp-v3": "^3.0"`

To decide wheter use [v2 ](https://flysystem.thephpleague.com/docs/adapter/sftp-v2/) or [v3 ](https://flysystem.thephpleague.com/docs/adapter/sftp-v3/)is "defined" here in the namespace `PhpseclibV2` of the class import:
https://github.com/pimcore/data-importer/blob/5d70698e7419e74761361841bffadf48a32ee530/src/DataSource/Loader/SftpLoader.php#L21-L22

**Comment by arulselvan008** [comment]
The field name is not visible while mapping because the data object importer cannot map the input quantity value.

Does anyone have the answer?

The input is 10 kg, and the data component type is input quantity value.
My Pimcore community version is 10.5.11

**Comment by kingjia90** [comment]
> The field name is not visible while mapping because the data object importer cannot map the input quantity value.
> 
> 
> 
> Does anyone have the answer?
> 
> 
> 
> The input is 10 kg, and the data component type is input quantity value.
> 
> My Pimcore community version is 10.5.11

It doesn't seem related to this issue, i suggest you to open a new ~discussion in the core repository pimcore/pimcore, so that the entire community could help, or an~(saw https://github.com/pimcore/pimcore/discussions/14587#discussion-4943893) issue on this repo if it's a reproducible bug.
Please also check if #215 is related

**Comment by arulselvan008** [comment]
sure , thank you.
