### ISSUE TITLE
[Bug]: Command killed

### ISSUE THREAD

**Issue by jkdc** [pimcore/data-importer#314]
### Expected behavior

Complete the command bin/console datahub:data-importer:prepare-import ImporterProducto without problems

### Actual behavior

When I run the command bin/console datahub:data-importer:prepare-import ImporterProducto, the memory usage starts to increase over time and eventually crashes the command. The output generated shows that the command was in the process of loading data from a configured source and preparing queue items before it was killed.
`string(45) "Loading source data from configured source..."
string(42) "Loaded source data from configured source."
string(53) "Interpreting source file and preparing queue items..."
Killed
`
The command was attempting to move an XLSX file with 90000 rows (20,5mb) to the database. While this doesn't seem like an excessively large amount of data, I am still concerned about the issue.

### Steps to reproduce

Run command --> bin/console datahub:data-importer:prepare-import ImporterProducto

**Comment by jkdc** [comment]
I have identified the problem and it appears to be related to the phpoffice library. A similar issue has been reported on GitHub at https://github.com/PHPOffice/PhpSpreadsheet/issues/2781. In my case, the solution was to use a CSV file instead of an XLSX file.

**Comment by lukmzig** [comment]
Hi @jkdc, thank you for reporting this issue. Based on your comment it seems like this is not a Pimcore related bug, therefore we will close this issue for now.
