### ISSUE TITLE
[Improvement]: Replace deprecated flysystem-sftp with flysystem-sftp-v3

### ISSUE THREAD

**Issue by ascheider** [pimcore/data-importer#321]
### Improvement description

Since https://github.com/thephpleague/flysystem-sftp is deprecated, it should be replaced with the https://github.com/thephpleague/flysystem-sftp-v3
Some Bundles already use flysystem-sftp-v3 and i'm not able to use those bundles, because of this deprecated dependency in data importer.
Please upgrade dependency in newer version.

**Comment by lukmzig** [comment]
Closing this issue as the library was updated already
See here https://github.com/pimcore/data-importer/commit/0b2ed335b2bdfc07530e52bf4307fe44d07bf5d8
