### ISSUE TITLE
[Bug]: XHR request to start import fails

### ISSUE THREAD

**Issue by rjankiew** [pimcore/data-importer#328]
### Expected behavior

When starting import manually, the import should start.

### Actual behavior

Import does not start. XHR request fails:
![obraz](https://user-images.githubusercontent.com/89988908/234542152-c3d4cdd0-b55e-40fb-96b9-05a7e0ac61da.png)
![obraz](https://user-images.githubusercontent.com/89988908/234542274-a555cf33-93db-4710-ba42-f43df2352957.png)

Application redepoy sometimes resolves this issue. I'm not sure what could be the reason. As the request takes a long time, I suspect it might be connected to import file not being processed in time?

### Steps to reproduce

Upload a file to configured import and start import manually.

**Comment by dvesh3** [comment]
It works for me:
![image](https://github.com/pimcore/data-importer/assets/5137917/bd9d12aa-2559-43fd-878a-f88ec8e338a8)

Please make sure `preparation` & `processing` steps are performed correctly as defined [here](https://pimcore.com/docs/platform/Data_Importer/Import_Execution_Details).

**Comment by dvesh3** [comment]
Sorry, not able to reproduce. Feel free to continue the discussion.
