### ISSUE TITLE
[Bug]: Error using "As input quantity value" mapper

### ISSUE THREAD

**Issue by dbarattini-jkl** [pimcore/data-importer#340]
### Expected behavior

Map an input field as input quantity value with a static unit

### Actual behavior

Throws this exception:
`Status: 500 | Internal Server Error
URL: /admin/pimcoredataimporter/dataobject/config/load-transformation-result
Method: POST
Message: Attempted to call an undefined method named "setSettings" of class "Pimcore\Bundle\DataImporterBundle\Mapping\Operator\Factory\InputQuantityValue".
Trace: 
in /var/www/html/vendor/pimcore/data-importer/src/Mapping/MappingConfigurationFactory.php:69
#0 /var/www/html/vendor/pimcore/data-importer/src/Mapping/MappingConfigurationFactory.php(132): Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory->buildTransformationPipeline('Product', Array)
#1 /var/www/html/vendor/pimcore/data-importer/src/Mapping/MappingConfigurationFactory.php(111): Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory->loadMappingConfigurationItem('Product', Array, true)
#2 /var/www/html/vendor/pimcore/data-importer/src/Controller/ConfigDataObjectController.php(386): Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory->loadMappingConfiguration('Product', Array, true)
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(166): Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController->loadTransformationResultPreviewsAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Bundle\DataImporterBundle\Settings\ConfigurationPreparationService), Object(Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory), Object(Pimcore\Bundle\DataImporterBundle\DataSource\Interpreter\InterpreterFactory), Object(Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService))
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#8 /var/www/html/public/index.php(19): require_once('/var/www/html/v...')
#9 {main}
`

### Steps to reproduce

1. Create an import Job
2. Use CSV as file extension, semi-colon as delimiter
3. Add a mapping with a string input field
4. Select "as input quantity value" as Data Type inside Transformation Pipelines

**Comment by kingjia90** [comment]
Resolved by #345
