### ISSUE TITLE
[Bug]: Uncaught TypeError: pimcore.plugin.pimcoreDataImporterBundle.configuration.components.logTab is not a constructor

### ISSUE THREAD

**Issue by fkieffer** [pimcore/data-importer#343]
### Expected behavior

Accessing the settings of the data importer by clicking on it.

![image](https://github.com/pimcore/data-importer/assets/9280428/32eb6748-3ea7-45dd-bd0a-6a78207e6be2)

### Actual behavior

The settings are not displayed and we have the following error : 

![image](https://github.com/pimcore/data-importer/assets/9280428/4fe00e97-2afe-40f0-a375-de40bbe1c511)

### Steps to reproduce

Hi everyone,

I installed the datahub and data importer in the community version. When I am creating an data object importer and trying to open the setting I am getting the below error. 
pimcore.plugin.pimcoreDataImporterBundle.configuration.components.logTab is not a constructor

Any idea ? 

Pimcore version : v11.0.2
Data importer version : v1.8.1

Thank you in advance

**Comment by HansTenBrinke** [comment]
I ran into the same issue. Eventually I realized that PimcoreApplicationLoggerBundle was not enabled in my bundles.php, after adding it, things started working as expected.

**Comment by fkieffer** [comment]
Thank you very much @HansTenBrinke ! It was the same issue in my case.
