### ISSUE TITLE
[Bug]: console.log as error handling for invalid config

### ISSUE THREAD

**Issue by mattamon** [pimcore/data-importer#347]
### Expected behavior

If I click on the config a proper error message is shown.

### Actual behavior

If a field is invalid the error is just logged into the console
![image](https://github.com/pimcore/data-importer/assets/38959016/a6aa48ec-396c-4f67-aab8-62d8e9faad8d)

https://github.com/pimcore/data-importer/blob/1.x/src/Resources/public/js/pimcore/configuration/components/mapping/mappingConfiguration.js#L145-L146

### Steps to reproduce

1. Login into https://demo.pimcore.com/admin/
2. Go to data hub config
3. Open the console e.g. in Chrome
4. Click on the `car-import` config.
5. Check the console it looks like the following:
![image](https://github.com/pimcore/data-importer/assets/38959016/1421ef77-81b6-4230-aeb9-d0e53b27eb5d)

**Comment by dvesh3** [comment]
Fixed by #358
