### ISSUE TITLE
[Feature]: [Bug]: too many connections mysql error when import data through datahub importer 

### ISSUE THREAD

**Issue by bhagawatpal** [pimcore/data-importer#354]
### Feature description

[Bug]: too many connections mysql error when import data through datahub importer, I think missing of garbageCollector

**Comment by dvesh3** [comment]
Hi @bhagawatpal could you please try #366 if this fixes the `too many connections` issue at your end? thanks!

**Comment by dvesh3** [comment]
Fixed by #366
