### ISSUE TITLE
[Bug]: Field definition for field not found if field name starts with upper case for "If source is empty" unchecked option

### ISSUE THREAD

**Issue by judip** [pimcore/data-importer#369]
### Expected behavior

Data target type "Direct" should handle correctly field name starts with lower and upper case in object definition.

### Actual behavior

Now only fields name with lower case are handle correctly becasue line 141 (file data-importer/src/Mapping/DataTarget/Direct.php)
$fieldName = lcfirst(str_replace('get', '', $getter));
This code converts always field name to lower case and then reports error: Field definition for field "x" not found.

### Steps to reproduce

Import any data for direct type and unchecked checkbox "If target is not empty" or "If source is empty".

**Comment by eciosk** [comment]
Same here.
Pimcore 11.0.12
Data-importer 1.8.4

**Comment by dvesh3** [comment]
Regression of #361
