### ISSUE TITLE
[Bug]: Error preparing Import: Warning: simplexml_load_string(): Entity: line 2: parser error : internal error: Huge input lookup

### ISSUE THREAD

**Issue by dannycao-2d** [pimcore/data-importer#372]
### Expected behavior

In Pimcore I upgraded the following variables:

```
upload_max_filesize = 500M
memory_limit = 500M
post_max_size = 500M

```
in php.ini at /usr/local/etc/conf.d/20-pimcore.ini using Pimcore 10.6.9. With data-importer version 1.8.4. Afterwards I restarted pimcore. In PimCore I can see the variables are changed:

![image](https://github.com/pimcore/data-importer/assets/138127873/aa3a23ec-f93a-44e4-8bc0-8903db2a7932)

### Actual behavior

Error preparing Import: Warning: simplexml_load_string(): Entity: line 2: parser error : internal error: Huge input lookup

### Steps to reproduce

Upload .xlsx file bigger than 2MB > Execute.

**Comment by dvesh3** [comment]
@dannycao-2d Could you please share the complete stack trace? as it seems not related to data importer itself.
