### ISSUE TITLE
[Bug]: AsDate should always return Carbon or null

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/data-importer#388]
### Expected behavior

If input is empty string, null should be returned.

### Actual behavior

The empty string is returned.

### Steps to reproduce

Use Transformation Pipeline As Date. Import empty string.

Pimcore\Bundle\DataImporterBundle\Mapping\Operator\Factory\Date.php (around line:50):

should read:

        foreach ($inputData as &$data) {
            if (!empty($data)) {
                $data = \Carbon\Carbon::createFromFormat($this->format, $data);
            } else {
                $data = null;
        }

**Comment by fashxp** [comment]
could you please provide a PR. thx.

**Comment by morgannilsson** [comment]
[DataImport_Transform_Date.patch](https://github.com/pimcore/data-importer/files/14111472/DataImport_Transform_Date.patch)

**Comment by morgannilsson** [comment]
#391

**Comment by morgannilsson** [comment]
I am working on setting up a devenv for pimcore github. Will add a test case later.
