### ISSUE TITLE
Good afternoon, when adding an XML file, an error pops up

### ISSUE THREAD

**Issue by Makskknd** [pimcore/data-importer#40]
Good afternoon, when adding an XML file, an error pops up, the xml file is default, I can't understand what the reason is, I attach screenshots

![Скриншот 24-05-2021 173747](https://user-images.githubusercontent.com/43819391/119364203-553c8a00-bcb7-11eb-84df-097e3848257e.jpg)
![Скриншот 24-05-2021 173802](https://user-images.githubusercontent.com/43819391/119364206-566db700-bcb7-11eb-8818-05f203bdbc2c.jpg)
![Скриншот 24-05-2021 173820](https://user-images.githubusercontent.com/43819391/119364211-57064d80-bcb7-11eb-9b5c-a7725b8ad963.jpg)

**Comment by fashxp** [comment]
Looks like #32  ... can you verify?
Release will be published on wednesday.

**Comment by fashxp** [comment]
closed due to no response. feel free to reopen if problem still exists
