### ISSUE TITLE
[Feature]: PHP 8.3 support?

### ISSUE THREAD

**Issue by tmannherz** [pimcore/data-importer#408]
### Feature description

Are you planning to support PHP 8.3? Pimcore core supports it as of a couple months ago but the PHP version in this repo's compose.json file is currently locked to <=8.2: `"php": "~8.0.0 || ~8.1.0 || ~8.2.0"`.

https://github.com/pimcore/pimcore/pull/16589

**Comment by blankse** [comment]
I created a PR: https://github.com/pimcore/data-importer/pull/409

**Comment by blankse** [comment]
The PR is already merged. Only waiting for the 1.9.0 release.
