### ISSUE TITLE
[Bug]: Find parent by attribute - parent needs to be published

### ISSUE THREAD

**Issue by heigpa** [pimcore/data-importer#415]
### Expected behavior

Parent can be in unpublished state as well

### Actual behavior

Import only works if parent is already published

### Steps to reproduce

Login as admin
Import a xlsx file with variants via the data importer

followup of https://github.com/pimcore/data-importer/pull/375

**Comment by Corepex** [comment]
Closed since https://github.com/pimcore/data-importer/pull/416 is already merged
