### ISSUE TITLE
Error while installation 

### ISSUE THREAD

**Issue by vinitchopra12** [pimcore/data-importer#43]
I am getting the below error while installing this bundle. 

  "[ErrorException]
  Array to string conversion"

![image](https://user-images.githubusercontent.com/14720025/122644485-11f8fe00-d133-11eb-90b3-09774e5c411c.png)

I am using Pimcore v10 and PHP v8.0.5.

**Comment by fashxp** [comment]
can you provide more debug information, e.g. execute `cache:clear -vv`? 
and debug it further on your side, thanks.

**Comment by vinitchopra12** [comment]
Below is the command log details. And there no logs are captured apart from this.


$ ./bin/console cache:clear -vv

 // Clearing the cache for the dev environment with debug true

 // Warming up cache...

09:45:23 INFO      [php] User Deprecated: The "Scheb\TwoFactorBundle\Security\Authentication\Provider\TwoFactorAuthenticationProvider" class implements "Symfony\Component\Security\Core\Authentication\Provider\AuthenticationProviderInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead. ["exception" => ErrorException { …}]
09:45:23 INFO      [php] User Deprecated: The "Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator" class implements "Symfony\Component\Security\Core\Authentication\Provider\AuthenticationProviderInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead. ["exception" => ErrorException { …}]
 // Removing old build and cache directory...

 // Finished


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

**Comment by fashxp** [comment]
so no error anymore?

**Comment by vinitchopra12** [comment]
I have just remove the pimcore-scripts commands from composer.json and then it works for me.
 "Pimcore\\Composer::clearCache",
      "Pimcore\\Composer::installAssets"

Not sure what went wrong with these above command.
