### ISSUE TITLE
Problem with composer install

### ISSUE THREAD

**Issue by danielczestki** [pimcore/data-importer#44]
I have a problem with installing this package.
I get error:

Problem 1
    - Installation request for pimcore/data-importer ^1.1 -> satisfiable by pimcore/data-importer[v1.1].
    - Can only install one of: phpseclib/phpseclib[3.0.9, 2.0.8].
    - Can only install one of: phpseclib/phpseclib[2.0.8, 3.0.9].
    - Can only install one of: phpseclib/phpseclib[2.0.8, 3.0.9].
    - Conclusion: install phpseclib/phpseclib 2.0.8
    - Installation request for phpseclib/phpseclib (locked at 3.0.9) -> satisfiable by phpseclib/phpseclib[3.0.9].
    
But when I try to install phpseclib/phpseclib 2.0.8 I get

Problem 1
    - Installation request for phpseclib/phpseclib 2.0.8 -> satisfiable by phpseclib/phpseclib[2.0.8].
    - Conclusion: remove paragonie/constant_time_encoding v2.4.0
    - Conclusion: don't install paragonie/constant_time_encoding v2.4.0
    - phpseclib/phpseclib 2.0.8 requires paragonie/constant_time_encoding ^1 -> satisfiable by paragonie/constant_time_encoding[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4].
    - Can only install one of: paragonie/constant_time_encoding[v1.0.0, v2.4.0].
    - Can only install one of: paragonie/constant_time_encoding[v1.0.1, v2.4.0].
    - Can only install one of: paragonie/constant_time_encoding[v1.0.2, v2.4.0].
    - Can only install one of: paragonie/constant_time_encoding[v1.0.3, v2.4.0].
    - Can only install one of: paragonie/constant_time_encoding[v1.0.4, v2.4.0].
    - Installation request for paragonie/constant_time_encoding (locked at v2.4.0) -> satisfiable by paragonie/constant_time_encoding[v2.4.0].

DOes anybody know how to install this package ?

**Comment by fashxp** [comment]
works for us without problems. 
for me, composer installs following versions of these two bundles: 
- phpseclib/phpseclib:2.0.32 
- paragonie/constant_time_encoding:v2.4.0

**Comment by fashxp** [comment]
is seems you were able to install now? can you share your findings?

**Comment by fashxp** [comment]
maybe also php version problem, see #45 ?

**Comment by danielczestki** [comment]
I fixed it.

**Comment by fashxp** [comment]
could you share your findings for others?

**Comment by skoch-twocream** [comment]
I solved the problem by using Composer 2 and then resolving some conflicts:

```
$ php7.4 composer-stable.phar req pimcore/data-importer
>   Problem 1
>    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
>    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.

$  php7.4 composer-stable.phar req wikimedia/composer-merge-plugin

$  php7.4 composer-stable.phar req pimcore/data-importer --with-all-dependencies
> Using version ^1.1 for pimcore/data-importer
> ./composer.json has been updated
> Running composer update pimcore/data-importer --with-all-dependencies
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 6 installs, 3 updates, 1 removal
>   - Removing paragonie/constant_time_encoding (v2.4.0)
>   - Locking dragonmantank/cron-expression (v3.1.0)
>   - Upgrading hybridauth/hybridauth (v2.17.0 => v2.18.0)
>   - Locking league/flysystem (2.1.1)
>   - Locking league/flysystem-bundle (2.0.0)
>   - Locking league/flysystem-sftp (2.1.1)
>   - Locking league/mime-type-detection (1.7.0)
>   - Upgrading ocramius/package-versions (1.9.0 => 1.11.0)
>   - Downgrading phpseclib/phpseclib (3.0.9 => 2.0.32)
>   - Locking pimcore/data-importer (v1.1.2)
> Writing lock file
> Installing dependencies from lock file (including require-dev)
> Package operations: 6 installs, 3 updates, 1 removal
>   - Downloading ocramius/package-versions (1.11.0)
>   - Downloading league/mime-type-detection (1.7.0)
>   - Downloading hybridauth/hybridauth (v2.18.0)
>   - Downloading league/flysystem-bundle (2.0.0)
>   - Downloading pimcore/data-importer (v1.1.2)
>   - Removing paragonie/constant_time_encoding (v2.4.0)
>   - Upgrading ocramius/package-versions (1.9.0 => 1.11.0): Extracting archive
>   - Installing league/mime-type-detection (1.7.0): Extracting archive
>   - Downgrading phpseclib/phpseclib (3.0.9 => 2.0.32): Extracting archive
>   - Upgrading hybridauth/hybridauth (v2.17.0 => v2.18.0): Extracting archive
>   - Installing league/flysystem (2.1.1): Extracting archive
>   - Installing league/flysystem-sftp (2.1.1): Extracting archive
>   - Installing league/flysystem-bundle (2.0.0): Extracting archive
>   - Installing dragonmantank/cron-expression (v3.1.0): Extracting archive
>   - Installing pimcore/data-importer (v1.1.2): Extracting archive
```
