### ISSUE TITLE
Problem when enable bundle

### ISSUE THREAD

**Issue by danielczestki** [pimcore/data-importer#45]
daniel@daniel-dm:~/Web/extraleker.pim$ ./bin/console pimcore:bundle:enable PimcoreDataImporterBundle

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected 'FilesystemOperator' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/daniel/Web/extraleker.pim/vendor/pimcore/data-importer/src/Preview/PreviewService.php:30
Stack trace:
#0 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Pimcore\\Bundle\\...')
#1 [internal function]: spl_autoload_call('Pimcore\\Bundle\\...')
#2 /home/daniel/Web/extraleker.pim/vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ClassExistenceResource.php(84): class_exists('Pimcore\\Bundle\\...')
#3 /home/daniel/Web/extraleker.pim/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(353): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#4 /home/daniel/Web/extraleker.pim/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveInstanceofConditionalsPass.php(79): Symfony\Component\DependencyInjection\ContainerBuilder->getRe in /home/daniel/Web/extraleker.pim/vendor/pimcore/data-importer/src/Preview/PreviewService.php on line 30
daniel@daniel-dm:~/Web/extraleker.pim$

**Comment by fashxp** [comment]
what PHP version are you using? 
what Pimcore version?

**Comment by danielczestki** [comment]
Yes I see that I use PHP 7.3
I think this package should check PHP version becouse version 1.1 need PHP 7.4
