### ISSUE TITLE
[Logging] Less verbose logging if cron is not started

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-importer#47]
fills up log with unnecessary messages.

**Comment by fashxp** [comment]
fixed via https://github.com/pimcore/data-importer/commit/daddc08071b0128314ea957383cb2231c5fd2b23

**Comment by rjankiew** [comment]
@fashxp After the latest update, my logger is filled up with "Configuration 'XXX' is not active, skipping preparation execution.". Any chance on making it less verbose again?

**Comment by fashxp** [comment]
nothing changed there ... you probably just have inactive configurations for which you are calling the preparation...
