### ISSUE TITLE
Q&A: Unable to import Block Fields or Field Collection

### ISSUE THREAD

**Issue by vinitchopra12** [pimcore/data-importer#49]
Does this plugin supports Block or Field Collection Data Component? if yes, is there any example.

I have to one field called 'feature' & Image Gallery fields inside the block I want to import the data through CSV. 

Below is my class definition screenshot:
![image](https://user-images.githubusercontent.com/14720025/124275503-41126500-db60-11eb-9e89-11d86296de82.png)

**Comment by fashxp** [comment]
not out of the box. custom data target implementations might be necessary.

**Comment by horeca2** [comment]
Is it now possible to import Block Fields or Field Collection?
