### ISSUE TITLE
Error on Import - DataObject not found

### ISSUE THREAD

**Issue by mediafant** [pimcore/data-importer#51]
Hi there,

there is an Error on Import:

`15:02:31 ERROR     [DATA-IMPORTER] Error processing element: Pimcore\Loader\ImplementationLoader\Exception\UnsupportedException: Loader for "\Pimcore\Model\DataObject\alfa" was not found in /var/www/html/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/ImplementationLoader.php:107`

And in Application Logger there is this message:
`Error processing element: Loader for "\Pimcore\Model\DataObject\alfa" was not found`

But class "alfa" is created and definitely available.

Fresh install ob pimcore 10.0.6, fresh dataHubBundle, fresh dataImporterBundle

Create a simple csv like:

```csv
id,key,first,second
100,caesar,caesar,Sub-caesar
101,dora,dora,Sub-dora
```

Create DataObject-Class "alfa" with two fields "first", "second"

Create new Datahub/DataObjectImporter "alfa"

*DataSource*
Asset /alfa.csv
FileFormat: CSV

*Import Settings*
*Resolver*
Class "alfa"
ElementLoading: "no Loading"
LocationStrategy: StaticPath => /Alfa

*Processing*
Execution: Sequential
DataIndex: key[1]
Check: x

*Mapping*
- key
- first
- second

Start Manual and then on commandline:
$ php ./bin/console datahub:data-importer:process-queue-sequential

`Processing 2 items sequentially

 0/2 [>---------------------------]   0%15:02:31 ERROR     [DATA-IMPORTER] Error processing element: Pimcore\Loader\ImplementationLoader\Exception\UnsupportedException: Loader for "\Pimcore\Model\DataObject\alfa" was not found in /var/www/html/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/ImplementationLoader.php:107
Stack trace:
#0 /var/www/html/vendor/pimcore/pimcore/lib/Model/Factory.php(51): Pimcore\Loader\ImplementationLoader\ImplementationLoader->build('\\Pimcore\\Model\\...', Array)
#1 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Factory/DataObjectFactory.php(59): Pimcore\Model\Factory->build('\\Pimcore\\Model\\...')
#2 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(183): Pimcore\Bundle\DataImporterBundle\Resolver\Factory\DataObjectFactory->createNewElement()
#3 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(153): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadOrCreateAndPrepareElement(Array)
#4 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(132): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processElement('alfa', Array, Object(Pimcore\Bundle\DataImporterBundle\Resolver\Resolver), Array)
#5 /var/www/html/vendor/pimcore/data-importer/src/Command/SequentialProcessQueueCommand.php(63): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processQueueItem(247)
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(299): Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(996): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(295): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/bin/console(46): Symfony\Component\Console\Application->run()
#13 {main}
15:02:31 ERROR     [DATA-IMPORTER] Error processing element: Pimcore\Loader\ImplementationLoader\Exception\UnsupportedException: Loader for "\Pimcore\Model\DataObject\alfa" was not found in /var/www/html/vendor/pimcore/pimcore/lib/Loader/ImplementationLoader/ImplementationLoader.php:107
Stack trace:
#0 /var/www/html/vendor/pimcore/pimcore/lib/Model/Factory.php(51): Pimcore\Loader\ImplementationLoader\ImplementationLoader->build('\\Pimcore\\Model\\...', Array)
#1 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Factory/DataObjectFactory.php(59): Pimcore\Model\Factory->build('\\Pimcore\\Model\\...')
#2 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(183): Pimcore\Bundle\DataImporterBundle\Resolver\Factory\DataObjectFactory->createNewElement()
#3 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(153): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadOrCreateAndPrepareElement(Array)
#4 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(132): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processElement('alfa', Array, Object(Pimcore\Bundle\DataImporterBundle\Resolver\Resolver), Array)
#5 /var/www/html/vendor/pimcore/data-importer/src/Command/SequentialProcessQueueCommand.php(63): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processQueueItem(248)
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(299): Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(996): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(295): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/bin/console(46): Symfony\Component\Console\Application->run()
#13 {main}
 2/2 [============================] 100%

Processed 2 items.
`

There are no items in Folder "/alfa"

Andreas

**Comment by fashxp** [comment]
Duplicate #50
