### ISSUE TITLE
Changes to Classes not reflecting on the data importer 

### ISSUE THREAD

**Issue by afe038** [pimcore/data-importer#52]
Hi to all,

I had created a class Supplier (id=6) with a set of fields. Later, I had modified the Supplier class with adding two additional fields:

- Device (checkbox)
- DestinationCountry (multi-select Country)

![image](https://user-images.githubusercontent.com/40383143/124926141-76ee9800-dffd-11eb-9ccb-dba7ba6af7cf.png)

ISSUE: When I'm creating/defining a new data importer job, the additional fields (that I added later on) are not shown: 

![image](https://user-images.githubusercontent.com/40383143/124927325-ce413800-dffe-11eb-9494-2fa2a7358391.png)

On the DB, everything seems OK:

![image](https://user-images.githubusercontent.com/40383143/124927483-fa5cb900-dffe-11eb-9d75-edccd5a63eec.png)

Anyone having the same issue?

**Comment by fashxp** [comment]
only data types in the list of `DEFAULT_TYPE` and `NUMERIC` are supported as attributes for loading data... see also [here](https://github.com/pimcore/data-importer/blob/40676d773d839681c3b0148a669ca148a0b29a03/src/Mapping/Type/TransformationDataTypeService.php#L38)

Loading based on a boolean field or based on a multiselect doesn't make too much sense or is not possible that easy.
