### ISSUE TITLE
Importing QuantityValue column from Pimcore Grid Export

### ISSUE THREAD

**Issue by wujku** [pimcore/data-importer#53]
@fashxp I have QuantityValue attribute in Classification Store. 
Exported column have value with unit. 
How to import the modified values back to Pimcore?

I tried to do this with transformation pipeline, but with more attributes, it can be too complex.

<img width="721" alt="Zrzut ekranu 2021-07-12 o 11 08 28" src="https://user-images.githubusercontent.com/1288915/125264320-09e04880-e304-11eb-876c-4d1db9f084ae.png">

Is there an easier way to do this?

**Comment by fashxp** [comment]
When coming from grid export, then you have all attributes in separate columns of your CSV ... thus the pipeline needs to be done for every attribute. Right now there is no easier way for doing this. 
Any ideas, who to archive it in an easier way? 

If data source format can be a bit, different, you can use the `Classification Store Batch` data target. Added some more options, docs and examples in #59
