### ISSUE TITLE
Set FullPath not possible "Empty data source index"

### ISSUE THREAD

**Issue by HeicoSindel** [pimcore/data-importer#55]
Hi. 
I tried to import initial data and want to set the fullpath i get the error "Empty data source index"
in my csv i provide the fullpath (as //[root]/[folder]/[objectname])
the resolver config
- Element loading
   * Loading strategy : no loading (as initial it is not necessary)
- Element creation: 
   * Location strategy: find path (because its different related to the <folder>
   * Find strategy: path (as i have a field "FullPath" in my csv)
   * Data Source Index: FullPath[0]
   * Fallback path: "/[root]" (also tried only "/")
- Element location update: same as Element creation
- Element publishing: always publish

Could someone provide me an example on how to configure the data-importer to set the FullPath?

Thanks in advance

**Comment by fashxp** [comment]
fix see #57 

please be aware, that `find parent` strategy only loads the parent based on the path. so your fullpath must contain the path of the parent element only, not the full path of the data object to be imported.
