### ISSUE TITLE
Extending Transformation Pipeline Operators

### ISSUE THREAD

**Issue by jure-knezovic** [pimcore/data-importer#61]
Hi all,

I am using Data importer to import products from json file. However, there are a few places where we need to use custom transformation pipeline operators as simple ones don't suffice our needs. So, I followed the docs to create a new transformation pipeline operator.

1. Created PHP file (autoloaded extensions namespace in composer.json):

![image](https://user-images.githubusercontent.com/67332841/125752848-b5436381-0c1f-4130-a85c-67b0cf08dc61.png)

2. Created entry in global config/services.yaml

![image](https://user-images.githubusercontent.com/67332841/125752774-76fc011b-3d80-42ef-ba96-e088136618bb.png)

3. Created JS file

![image](https://user-images.githubusercontent.com/67332841/125752935-2e38c716-e990-4239-99e5-4e810c6c20b1.png)

This is the final folder setup with files that i have on my side

![image](https://user-images.githubusercontent.com/67332841/125753784-3f0bcda2-4604-40ae-ab0d-98acccdad8fa.png)

Using xDebug, i have found out that my testmapping is indeed loaded in MappingConfigurationFactory, however my frontend seems to be the same. It is like javascript file is not sent to frontend, or something similar.
![image](https://user-images.githubusercontent.com/67332841/125753195-04af8e51-3c99-4153-8bce-4fab478d2f59.png)

Do you have any idea what I might be doing wrong?
Also, if you have, can you provide us with an example of this scenario as that might help me quite a lot to fix it?

**Comment by fashxp** [comment]
is the JS file loaded? 

see for example [here](https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Loading_Admin_UI_Assets.html) for details

see also https://github.com/pimcore/pimcore/discussions/9781

**Comment by jure-knezovic** [comment]
Hi there,

That seems to be the problem on our side. Also, JS files should be placed somewhere where it is not symlinked. I think that this should be added to documentation, if possible?

I will close this issue as it is solved.

**Comment by fashxp** [comment]
can you please add a PR and add missing pieces of information to the docs ... they are also part of the repository. 
thx.
