### ISSUE TITLE
How to use the classification store and classification store batch in mappings?

### ISSUE THREAD

**Issue by bitfactory-justin-kouwenhoven** [pimcore/data-importer#67]
### Classification store

Im trying to import a document that has several columns that i want to map to a classification store.

<img width="1259" alt="Schermafbeelding 2021-07-22 om 15 25 40" src="https://user-images.githubusercontent.com/15174824/126646873-dbdc5288-d14e-4bdd-8d52-98d4a7699c06.png">

<img width="702" alt="Schermafbeelding 2021-07-22 om 15 26 59" src="https://user-images.githubusercontent.com/15174824/126646862-bfcb5ffb-3273-434f-a4c3-1b12aed3f31e.png">

<img width="876" alt="Schermafbeelding 2021-07-22 om 15 26 42" src="https://user-images.githubusercontent.com/15174824/126646870-8e1c78e2-72f7-46a1-a1cf-f62a864bfb1a.png">

When im trying to assign a data key the search popup is empty.
Am i missing something here?

### Classification store batch

How do you map several columns at once to a classification store batch?
When selecting multiple columns as source attributes the transformation preview results an array.
There is currently no transformer available to convert the array to an array with the correct key's.

```
[
    1-1 => 3,
]
```

<img width="833" alt="Schermafbeelding 2021-07-22 om 15 35 19" src="https://user-images.githubusercontent.com/15174824/126647925-15b97c82-bb70-45a3-b003-ab221117d2ca.png">

**Comment by fashxp** [comment]
ad 1) You types must match. You cannot import a default type to a number field. Use the transformation pipeline to transform your input data to a number. 

ad 2) as the comment already says, your input needs to be an array, where the keys are the group-id and the values are the values. also have a look at https://github.com/pimcore/data-importer/pull/59 for a bit more insights.

**Comment by bitfactory-justin-kouwenhoven** [comment]
@fashxp 
Thank you for the information, i got the classification store mapping working now.
