### ISSUE TITLE
[Classification Store] Conflict with class Inheritance setting

### ISSUE THREAD

**Issue by wujku** [pimcore/data-importer#69]
When I am trying to import data into nested product objects, data doesn`t save correctly.
For example, I have two key definitions (text input) in one group of Classification Store, mapped by import configuration. 
Firstly, I imported ParentItem1 with non empty values and imported two child items with other values for key definitions after few days. When I opened a child product, I saw the data from the parent in grayed out fields instead of the imported ones. The data in the database table was also not saved.

Objects Tree:

```
|- ParentItem1
|-- ChildItem1
|-- ChildItem2
```

Product class has "Allow inheritance" option checked.

**Comment by fashxp** [comment]
can you provide more specific steps for reproducing? 

since data-importer is using Pimcore PHP API, it might be a general Pimcore problem? maybe you can try to create a script that does exactly that for easier debugging. the assignment in data-importer happens [here](https://github.com/pimcore/data-importer/blob/40676d773d839681c3b0148a669ca148a0b29a03/src/Mapping/DataTarget/Classificationstore.php#L65)

**Comment by wujku** [comment]
@fashxp Thanks, I will try to verify it and I will come back with information.

**Comment by fashxp** [comment]
@wujku any updates

**Comment by fashxp** [comment]
@wujku  ping

**Comment by wujku** [comment]
@fashxp I do not have time to verify this problem at the moment, I will try to check it soon.

**Comment by kkowalczuklemon** [comment]
I have a similar problem. I'm trying create or update child object. A different group is not added to the child's classification store and the key data are not entered. The data is also not in the database. I have inheritance and variants set in the object.

Steps to reproduce:

1. Create a parent object
2. Add a group from the classification store to the parent
3. Enter the data into the fields from the classification store.
3. In the importer configuration set Resolver -> Element Creation -> Location Strategy to Find Parent
4. In Mapping set different classification store group than in the parent as data target

In Mapping I didn't use group using in parent. When I try to update a child object, I have the same situation.

**Comment by fashxp** [comment]
could you guys please check if https://github.com/pimcore/pimcore/pull/11270 fixes that issue?

**Comment by fashxp** [comment]
closed due to inactivity
