### ISSUE TITLE
Deltacheck is not working

### ISSUE THREAD

**Issue by psuhane** [pimcore/data-importer#70]
Attribute name in the configuration is being saved as attribute 'doDeltaCheckCheck' but in InterpreterFactory attribute 'doDeltaCheck' is being used.

https://github.com/pimcore/data-importer/blob/13d787c500b750f1496454ad9d6b567a260467a8/src/DataSource/Interpreter/InterpreterFactory.php#L49

https://github.com/pimcore/data-importer/blob/35b4fec86ab7245ac77e03fc9c41a41bf7f94625/src/Resources/public/js/pimcore/configuration/components/importSettings.js#L217

**Comment by fashxp** [comment]
fixed via #78
