### ISSUE TITLE
Data-Import (v 1.1.3, DataHub v 1.0.5, Pimcore 10.0.8) not working

### ISSUE THREAD

**Issue by HeicoSindel** [pimcore/data-importer#72]
Hi. 
After some issues regarding the permissions (i think i have solved it) - i am able to import data - only on the root directory (with file on asset and push data with postman) - not creating the FullPath. 
I tried any possible constellation by using and setting the resolver. 

I send data with the FullPath in the way "//[root]/[sub1]/[key]" 
The resolver is set to 
- Loading strategy: no loading (because of first import)
- Element creation: Find Path - Path - [my-fullpath-field]
- Element Location update: Find Path - Path - [my-fullpath-field]

New for me is the field "Data index of ID field" within the "Processing setting" - what does this means? it is not explaint anywhere...

Thx for help

**Comment by HeicoSindel** [comment]
additional info: it seems that the folders are not created automatically if they do not exist...

**Comment by fashxp** [comment]
no, folders are not created. that's why there is the fallback path that can be set. 
but an additional location strategy `FindOrCreateFolder` might be a useful addition, anyone in with a PR?

**Comment by HeicoSindel** [comment]
I used the location strategy `Find Parent` - and it might be very useful the have a function like `FindOrCreateFolder` :-)
In the meantime, I will make do with a workaround via the DataHub (mutations).
