### ISSUE TITLE
Folders are not created dynamically during import

### ISSUE THREAD

**Issue by HeicoSindel** [pimcore/data-importer#73]
it seems that the folder structure is not created automatically if it does not exist....
have I overlooked another configuration here?

**Comment by fashxp** [comment]
I guess you are referring to the location strategy `FindParent`? 

no, folders are not created. that's why there is the fallback path that can be set. `FindParent` is also not restricted for folders, could also load any other data object (to create hierarchies). 
but an additional location strategy `FindOrCreateFolder` might be a useful addition, anyone in with a PR?

**Comment by QuarkWave** [comment]
Hi,

I did fix that in a way but I assume that `fallbackPath `is always a `folder `type. 
I m not sure that  i m familiar enough to deal with a complex PL but if we just add a checkbox "Is a folder" next to the "FallBack Path" and i can use that to trigger my code I could make it happen.

Not nice enough ?

**Comment by Timonwatteny** [comment]
Any update on this yet? It seems that this was functionality that we had in the CSV import so it would be nice to have it in Pimcore X as well.

**Comment by jeykodev** [comment]
@kingjia90 Thanks for PR! Why is this feature still not available in 1.4 branch, only in 1.x?

**Comment by kingjia90** [comment]
@jeykodev you're welcome, i am glad to be of help. This git issue was an improvement/new feature and according to [CONTRIBUTING.md](https://github.com/pimcore/pimcore/blob/10.x/CONTRIBUTING.md) it must be in the 1.x branch.

**Comment by jeykodev** [comment]
@kingjia90 ok, I understand. So I guess it depends on @fashxp if we get this feature in the mail 1.4 branch? ;)

**Comment by fashxp** [comment]
Semver requires: new features/improvements go into feature branches and minor releases, not bugfix releases.
