### ISSUE TITLE
Unable to create new loading strategy

### ISSUE THREAD

**Issue by moiashvin** [pimcore/data-importer#74]
Hi,

I am using Pimcore X with the DataHub. I want to add a new Loading Strategy (to search by calculated field) in the DataObjects imported as per instructions here: https://pimcore.com/docs/data-importer/current/Extending.html

1. I created the new strategy RiwStrategy  (see attached php file)

`<?php
namespace App\Importer\Resolver\Load;
use Pimcore\Bundle\DataImporterBundle\Exception\InvalidConfigurationException;
use Pimcore\Model\Element\ElementInterface;
use Pimcore\Bundle\DataImporterBundle\Resolver\Load\AbstractLoad;

class RiwStrategy extends AbstractLoad
{

    public function loadElementByIdentifier($identifier): ?ElementInterface
    {
       $className = $this->getClassName();
        return $className::getById($identifier);  //I ill change this later to match by calculated field
    }

    public function loadFullIdentifierList(): array
    {
        $sql = sprintf('SELECT `riw` FROM object_%s', $this->dataObjectClassId);   //changed to use calculated field
        return $this->db->fetchCol($sql);
    }
}`
``

`

2. I added RiwStrategy as Service

`App\Importer\Resolver\Load\RiwStrategy:`
        public: true
        tags:
            - { name: "pimcore.datahub.data_importer.resolver.load", type: "riw" `}`

Problem is this new strategy is not in the list on the Import Settings -> Element Loading -> Loading Strategy drop-down.

Is there anything else I need to do?

Thanks for help.

**Comment by moiashvin** [comment]
need to add js

**Comment by fashxp** [comment]
could you please add a note to the [docs](https://github.com/pimcore/data-importer/edit/main/doc/06_Extending.md) that would have helped you? 
thanks...
