### ISSUE TITLE
Q&A: How to handle arrays in the transformation pipeline?

### ISSUE THREAD

**Issue by jeykodev** [pimcore/data-importer#76]
Hi everyone, 

I have problems with arrays in the data importer. In the [documentation](https://pimcore.com/docs/data-importer/current/Configuration/File_Formats.html) it is mentioned that we have to consider possible arrays in multidimensional import files (xml or json) by ourself, but I have no idea how to do this. 

Lets say we have the following xml structure: 

```
...
<name>Demo name</name>
<prices>
    <netprice>429.89</netprice>
    <grossprice>582.89</grossprice>
    <tax>153</tax>
</prices>
...
```

Now, I want to map the fields to my dataobject. `name` for example can be mapped directly, okay. But how about the `prices`? I would expect an operator in the transformation pipeline, where I can select each array item, so that they can be mapped to the dataobject datafields separately.

Do I get something wrong here or is an operator like this missing? 

Thanks for your feedback. :)

**Comment by fashxp** [comment]
Hi, 
right now, there is no such operator ... but yes, would be a nice addition. Anyone ready to contribute? 

Cheers...

**Comment by jeykodev** [comment]
@fashxp thanks for your reply! I will see what I can do, maybe I can make a PR.

**Comment by oriiyx** [comment]
Hey @fashxp just checking if anything has been done to select array items?

I've checked it in the demo store - but there's no such example there, documentation has 0 information regarding it - and while researching myself I found no option that could get me the result.

Just checking if I missed anything by any chance?

**Comment by fashxp** [comment]
not that I know of.
