### ISSUE TITLE
Can't install in the official demo, as it uses PHP8 (problem with league/flysystem-sftp dependency)

### ISSUE THREAD

**Issue by itpilotdk** [pimcore/data-importer#82]
Can't install on Pimcore10.x. Set of packages incompatible with PHP8 (according to composer at least). Please fix. 

![image](https://user-images.githubusercontent.com/88710986/128838394-d26c1e6e-733f-4743-94d8-897d09d479ea.png)

**Comment by brusch** [comment]
Please read the error message carefully .... 

![image](https://user-images.githubusercontent.com/142037/128839535-b5ee2dcf-d163-4d81-af09-69734fc52786.png)

**Comment by itpilotdk** [comment]
Thank you for the instant response. I got it working just fine. But I would prefer (for the benefit of everyone), that the official demo was shipped with a compatible set of composer/lockfiles for the current maintained version. 

It looks like the data-importer composer settings haven't ben updated for Pimcore 10.x:)

**Comment by brusch** [comment]
They are updated, however, this depends on your `composer.lock`, nothing we can do here ...

**Comment by itpilotdk** [comment]
It's not my lockfile, its the one shipped with the V10 demo. Sorry if I should have submitted the issue in the demo repo :-)
 
But the demo (which is PHP8) is in fact shipping an incompatible PHP 7.x requirement in the composer.lock:)

https://github.com/pimcore/demo/blob/10.x/composer.lock#L3455 
![image](https://user-images.githubusercontent.com/88710986/128842872-dad1d163-3358-4122-9e94-37a528149245.png)

Thanks again for the lightning fast response time. I have solved my local issue. Was just reporting for others.

**Comment by brusch** [comment]
data-importer has some higher requirements on existing dependencies, it doesn't make sense to raise the requirements for the demo itself, just in case someone installs data-importer. That's dependency management.
