### ISSUE TITLE
[Improvement]: Cleanup objects: make "id" field configurable

### ISSUE THREAD

**Issue by aweichler** [pimcore/data-importer#84]
### Improvement description

Currently it is only possible to use the cleanup functionality with an id field (where id is an pimcore id).
It would be better to have the "id" field configurable.
For example when I have a EAN number of an product, the "id" field would be the "EAN" field of object.

If there would be an new field "ID field" after "Data index of ID field:" (in "Import Settings" -> "Process Settings"), where you can choose the field of the class, it would be possible to load the objects based on that field.

What do you think?
I could provide an pull request.

**Comment by fashxp** [comment]
sounds reasonable!
but isn't that already possible? doc says
```
Cleanup jobs are simpler and consist of following steps:

Look for existing data element based on loading strategy.
Cleanup element (unpublish or delete) based on cleanup strategy.
```

thus, if you define a element loading strategy based on the EAN attribute,  and then also define the EAN field as the ID for the cleanup, it should do already exactly what you are trying to archive. 

can you verify that and maybe we need to make the docs more clear?

**Comment by aweichler** [comment]
You are right, it is possible already, I think I have done some mistake, sorry.
But it only works if i change the [line](https://github.com/pimcore/data-importer/blob/6255f87c602335fddd6fea60025bde321903dc05/src/Processing/ImportProcessingService.php#L143)
`$this->cleanupElement($configName, $queueItem['data'], $resolver, $config['interpreterConfig']['cleanup'] ?? []);`
to
`$this->cleanupElement($configName, $queueItem['data'], $resolver, $config['processingConfig']['cleanup'] ?? []);`.

The configuration for the cleanup strategy is stored in "processingConfig" -> "cleanup".
Could it be an error or is something wrong with my configuration?

**Comment by fashxp** [comment]
you are right ... just fixed it, see https://github.com/pimcore/data-importer/pull/86

**Comment by aweichler** [comment]
Cool. Thank you very much :)
