### ISSUE TITLE
[Bug]: Could not map Source Data to ObjectBrick

### ISSUE THREAD

**Issue by HeicoSindel** [pimcore/data-importer#85]
### Expected behavior

I have configured an ObjectBrick (dimensions) with 7 Fields of Type Quantiy Values.
These ObjectBrick i have configured in my data object (products) with the attribute "QUANT"

After selecting the source attribute of the input data field (netweight, with sample value of "2,000 KG") and selecting in Data Target the type "Direct" the object brick - or the attributes within it should be suggested as possible Mapping in "Field Name"

### Actual behavior

the Field Name only suggest other (text) fields
i tried to send an array [2,000 KG] and try to transform it before to an QuantityValue but there i get an error there

### Steps to reproduce

see behavior...

**Comment by fashxp** [comment]
you need to transform it to quantity value, otherwise it will not suggest you quantity value attributes. 
what error do you get?

**Comment by HeicoSindel** [comment]
Without Transformation
![image](https://user-images.githubusercontent.com/74646710/131328306-938f0539-ba08-4849-a162-f61b13ee0419.png)

With Transformation "As Quantity Value"
![image](https://user-images.githubusercontent.com/74646710/131328429-2e7ba9dd-a49b-4625-81ec-5b7a42627085.png)

**Comment by fashxp** [comment]
use this transformation pipeline: 
1) `as Arrray` (you need to tell the transformation pipeline, that you having an array at the beginning)
2) `As Quantity Value`

**Comment by HeicoSindel** [comment]
thx cf - that's it... :-)

**Comment by fashxp** [comment]
if you have any suggestion for improving the docs, PRs are welcome ;-)

**Comment by HeicoSindel** [comment]
Yes - i will also contribute on improving some docs - at least with examples...
