### ISSUE TITLE
[Feature]: Data exporter

### ISSUE THREAD

**Issue by Yivan** [pimcore/data-importer#98]
### Feature description

Hello,

I don't know too much where to post this, so I get a try here.
Pimcore 10 brings use DataHub with this really great data-importer, but we are left for the other way export the data.

Actually in the open-source Pimcore ecosystem choices are:
- using the grid export (fine for GUI export, but for process/batch this is not convenient), being able to trigger grid configuration export from cli command could be a good new improvement (I will open a feature request in pimcore repository)
- using https://github.com/elements-at/ExportToolkit, which is great, but more a "toolkit" (like it's name : )) ) and missing the many operators and getters we have with the data-importer.
- using https://github.com/w-vision/DataDefinitions, but for now this is not ready for Pimcore 10

So question is, is there any data-exporter on the roadmap ? Somethings planned on this subject for Pimcore ?
There is already a good GUI for data-importer which could be reused for exporter, forking from data-importer to create a data-exporter will make coherent import/export system native and open-source for Pimcore.

Thanks for reading me.

**Comment by fashxp** [comment]
The primary choice for exposing data to the outside world is Datahub GraphQL. 
If you need file based export, you can use csv/xls export in Grids (which should also be usable from CLI with some customization), or you can use [Simple File Export](https://pimcore.com/docs/data-hub-file-export/current/) of our enterprise offering. 
Besides that, there are a couple of additional extensions (data definitions, data director, etc.) for data export around in the ecosystem.

**Comment by Yivan** [comment]
Thanks for the Simple File Export suggestion !
