### ISSUE TITLE
[Improvement]:  Validate or extend column length for configurations name

### ISSUE THREAD

**Issue by ghost** [pimcore/data-importer#99]
### Improvement description

Currently the column **configName**  from the table **bundle_data_hub_data_importer_queue** has a maximum of characters of 50. It would be good to increase this or to add some kind of validation that does not allow to create a configuration with more than 50 characters.
What happens now is that data importer would allow such a configuration name be created but it would failed silently when executing as the configuration name will be trimmed.
When for example the cron with the command **bin/console datahub:data-importer:process-queue-sequential**  runs will fail completely since the trimmed configuration does not exists.

Example Output with a configuration with a name like "tgi_06102021_1000_experience_product_strike_prices_back":

`RITICAL  [console] Error thrown while running command "datahub:data-importer:process-queue-sequential". Message: "Configuration tgi_06102021_1000_experience_product_strike_prices does not exist." ["exception" => Exception { …},"command" => "datahub:data-importer:process-queue-sequential","message" => "Configuration tgi_06102021_1000_experience_product_strike_prices does not exist."]

In ConfigurationPreparationService.php line 32:

  Configuration tgi_06102021_1000_experience_product_strike_prices does not exist.`

**Comment by fashxp** [comment]
fixed with #122 and #137
